
spring.application.name=notasnurv3_api
spring.profiles.active=local

# Datos de la DB
spring.datasource.url=jdbc:postgresql://ep-spring-dawn-acq476b8-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kIJ6aRrO9pnz

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configuración de Timezone para Bolivia
spring.jackson.time-zone=GMT-4

# Configuración del JWT
security.jwt.secret-key=e4e1242cfe1ba12f08ae571909ddeaec3f4f09e86d3346a109acb4a75c5dcfde10cec6af747ef66fad68d9fc007848e57c0be9d5df293d006f1fc8c3a8778cbb
security.jwt.expiration-time=86400000

