spring.application.name=notasnurv3_api
spring.profiles.active=local

# Datos de la DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configuración de Timezone para Bolivia
spring.jackson.time-zone=GMT-4

# Configuración del JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=86400000